version: "3.8"

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "3002:3002"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
